import React, { useState, useEffect, useMemo } from 'react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import { Target, TrendingUp, BarChart3, Settings, History, Play, Trophy, Calendar, ChevronRight, Zap, Database, CheckCircle } from 'lucide-react';
import { loadSeasonData } from './data';
import { rollingAccuracy, wOffFromWeights, fitHfa } from './rolling';

// Honest-accuracy discipline (see scripts/honest_backtest.py + CLAUDE.md):
// fit weights on FIT_SEASON, and the ONLY accuracy ever shown to users is
// those frozen weights applied to TEST_SEASON (untouched during fitting).
const FIT_SEASON = 2024;
const TEST_SEASON = 2025;
const PREDICT_SEASON = 2026; // season whose upcoming games we predict
const VEGAS_BASELINE = 63.0; // always-pick-Vegas-favorite hit rate, for context

// Pure scoring — identical math for fit and test seasons.
function scoreTeam(stats: any, w: any): number {
  const offense = (
    (stats.offense.points_per_game / 35) * 0.4 +
    (stats.offense.passing_yards / 300) * 0.3 +
    (stats.offense.rushing_yards / 150) * 0.2 +
    stats.offense.red_zone_efficiency * 0.1
  ) * (w.offense / 100);
  const defense = (
    (1 - (stats.defense.points_allowed_per_game / 35)) * 0.4 +
    (1 - (stats.defense.yards_allowed / 450)) * 0.3 +
    (stats.defense.turnovers_forced / 30) * 0.2 +
    (stats.defense.sacks / 50) * 0.1
  ) * (w.defense / 100);
  const special = (
    stats.special_teams.fg_percentage * 0.6 +
    (stats.special_teams.punt_return_avg / 15) * 0.2 +
    (stats.special_teams.kick_return_avg / 30) * 0.2
  ) * (w.special_teams / 100);
  return Math.max(0, offense + defense + special);
}

// NOTE: the old accuracyOn() scored completed games with SEASON-END team
// stats — a data leak that inflated accuracy (68.4% vs the honest ~60%).
// Backtest/optimizer accuracy now comes from ./rolling (prior-weeks-only),
// which mirrors scripts/honest_backtest.py. scoreTeam above is still used
// for FUTURE-game predictions (Predict tab), where season-to-date stats are
// legitimate — see PROGRESS.md T3.

const NFLPredictionApp = () => {
  const [nflData, setNflData] = useState<any>(null);       // FIT_SEASON (2024)
  const [testData, setTestData] = useState<any>(null);     // TEST_SEASON (2025)
  const [predictData, setPredictData] = useState<any>(null); // PREDICT_SEASON games + best-available stats
  const [loading, setLoading] = useState(true);
  const [weights, setWeights] = useState({
    offense: 33.33,
    defense: 33.33,
    special_teams: 33.34
  });
  const [activeTab, setActiveTab] = useState('predict');
  const [selectedGame, setSelectedGame] = useState<any>(null);
  const [backtestResults, setBacktestResults] = useState<any>(null);
  const [optimalWeights, setOptimalWeights] = useState<any>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);

  // Real NFL data now comes from public/data/*.json (generated by
  // scripts/fetch_data.py) via loadSeasonData — no embedded stats.
  useEffect(() => {
    Promise.all([
      loadSeasonData(FIT_SEASON),
      loadSeasonData(TEST_SEASON),
      loadSeasonData(PREDICT_SEASON),
    ])
      .then(([fit, test, predictSeason]) => {
        setNflData(fit);
        setTestData(test);

        // Predict PREDICT_SEASON games. If that season has no team stats yet
        // (preseason), degrade to TEST_SEASON's season-end stats — labeled.
        const has2026Stats = Object.keys(predictSeason.teams).length > 0;
        const predict = has2026Stats
          ? { ...predictSeason, statsSeason: PREDICT_SEASON, degraded: false }
          : {
              teams: test.teams,
              upcoming_games: predictSeason.upcoming_games,
              statsSeason: TEST_SEASON,
              degraded: true,
            };
        setPredictData(predict);
        setSelectedGame(predict.upcoming_games[0] ?? null);
        setLoading(false);
      })
      .catch((err) => {
        console.error('Failed to load season data', err);
        setLoading(false);
      });
  }, []);

  const adjustWeights = (category, value) => {
    const newWeights = { ...weights };
    const oldValue = weights[category];
    const difference = value - oldValue;
    
    newWeights[category] = value;
    
    const otherCategories = Object.keys(weights).filter(key => key !== category);
    const totalOtherWeights = otherCategories.reduce((sum, key) => sum + weights[key], 0);
    
    if (totalOtherWeights > 0) {
      otherCategories.forEach(key => {
        const proportion = weights[key] / totalOtherWeights;
        newWeights[key] = Math.max(0, weights[key] - (difference * proportion));
      });
    }
    
    const total = Object.values(newWeights).reduce((sum, val) => sum + val, 0);
    if (Math.abs(total - 100) > 0.01) {
      const adjustment = (100 - total) / otherCategories.length;
      otherCategories.forEach(key => {
        newWeights[key] += adjustment;
      });
    }
    
    Object.keys(newWeights).forEach(key => {
      newWeights[key] = Math.round(newWeights[key] * 100) / 100;
    });
    
    setWeights(newWeights);
  };

  const calculateTeamScore = (teamAbbr) => {
    if (!predictData?.teams?.[teamAbbr]) return 0;
    return scoreTeam(predictData.teams[teamAbbr], weights);
  };

  // Honest optimizer: FIT on 2024, then the headline number is those frozen
  // weights applied to the untouched 2025 season. Best config is chosen by
  // the 2024 fit — never by the 2025 score (that would be the trap).
  const findOptimalWeights = async () => {
    if (!nflData || !testData) return;
    setIsAnalyzing(true);
    setOptimalWeights(null);

    const testCombinations = [];
    for (let offense = 20; offense <= 70; offense += 10) {
      for (let defense = 20; defense <= 70; defense += 10) {
        const specialTeams = 100 - offense - defense;
        if (specialTeams >= 10 && specialTeams <= 70) {
          testCombinations.push({ offense, defense, special_teams: specialTeams });
        }
      }
    }

    let bestFit = -1;
    let bestWeights = null;
    let bestHfa = 0;
    const results = [];

    // Rolling (prior-weeks-only) evaluation — no season-end leak. Each combo
    // is fit on 2024 (hfa chosen in-sample there) and the SAME frozen config
    // is scored on the untouched 2025 season.
    for (const w of testCombinations) {
      const wOff = wOffFromWeights(w);
      const fit = fitHfa(nflData.completed_games, wOff);              // 2024 in-sample
      const honest = rollingAccuracy(testData.completed_games, wOff, fit.hfa); // 2025 frozen
      results.push({
        weights: w,
        fit: fit.pct.toFixed(1),
        honest: honest.pct.toFixed(1),
      });
      if (fit.pct > bestFit) {   // pick by FIT season only
        bestFit = fit.pct;
        bestWeights = w;
        bestHfa = fit.hfa;
      }
      await new Promise(resolve => setTimeout(resolve, 60));
    }

    // Frozen best (chosen on 2024) applied to the untouched 2025 season.
    const honestBest = rollingAccuracy(testData.completed_games, wOffFromWeights(bestWeights), bestHfa);
    results.sort((a, b) => parseFloat(b.fit) - parseFloat(a.fit));

    setOptimalWeights({
      best: bestWeights,
      fitAccuracy: bestFit.toFixed(1),           // in-sample 2024 — never the headline
      honestAccuracy: honestBest.pct.toFixed(1), // 2025 — THE number users see
      vegas: VEGAS_BASELINE.toFixed(1),
      fitSeason: FIT_SEASON,
      testSeason: TEST_SEASON,
      allResults: results.slice(0, 5),
      totalTested: testCombinations.length,
    });

    setIsAnalyzing(false);
  };

  const prediction = useMemo(() => {
    if (!selectedGame || !predictData) return null;

    const homeScore = calculateTeamScore(selectedGame.home_team);
    const awayScore = calculateTeamScore(selectedGame.away_team);

    const winner = homeScore > awayScore ? selectedGame.home_team : selectedGame.away_team;
    const confidence = Math.min(95, 55 + (Math.abs(homeScore - awayScore) * 200));

    return {
      winner: predictData.teams[winner],
      homeTeam: predictData.teams[selectedGame.home_team],
      awayTeam: predictData.teams[selectedGame.away_team],
      homeScore: homeScore.toFixed(3),
      awayScore: awayScore.toFixed(3),
      confidence: confidence.toFixed(1)
    };
  }, [selectedGame, weights, predictData]);

  // Backtest the user's CURRENT sliders on the untouched TEST_SEASON (2025)
  // — out-of-sample, the only honest way to show "how your model did".
  const runBacktest = () => {
    if (!testData || !nflData) return;
    // Rolling (prior-weeks-only) — no season-end leak. Home-field advantage
    // is fit on 2024 so it isn't tuned on the 2025 season we're scoring.
    const wOff = wOffFromWeights(weights);
    const { hfa } = fitHfa(nflData.completed_games, wOff);
    const { pct, correct, total, rows } = rollingAccuracy(testData.completed_games, wOff, hfa);

    setBacktestResults({
      accuracy: pct.toFixed(1),
      season: TEST_SEASON,
      vegas: VEGAS_BASELINE.toFixed(1),
      correct,
      total,
      results: rows,
    });
  };

  const WeightSlider = ({ category, label, value, color }) => (
    <div className="space-y-3">
      <div className="flex justify-between items-center">
        <label className="text-lg font-semibold">{label}</label>
        <span className="text-2xl font-bold" style={{ color }}>{value.toFixed(1)}%</span>
      </div>
      <input
        type="range"
        min="0"
        max="100"
        step="0.1"
        value={value}
        onChange={(e) => adjustWeights(category, parseFloat(e.target.value))}
        className="w-full h-3 rounded-lg appearance-none cursor-pointer"
        style={{
          background: `linear-gradient(to right, ${color} 0%, ${color} ${value}%, rgba(255,255,255,0.2) ${value}%, rgba(255,255,255,0.2) 100%)`
        }}
      />
    </div>
  );

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-900 to-slate-800 text-white flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin w-16 h-16 border-4 border-orange-500 border-t-transparent rounded-full mx-auto mb-4"></div>
          <h2 className="text-2xl font-bold mb-4">Loading NFL 2024 Data</h2>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-900 to-slate-800 text-white">
      {/* Header */}
      <div className="bg-black/20 backdrop-blur-lg border-b border-white/10 p-4">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="bg-orange-500 p-3 rounded-xl">
              <Target className="w-8 h-8" />
            </div>
            <div>
              <h1 className="text-2xl font-bold">NFL Prediction Engine</h1>
              <p className="text-blue-200 flex items-center gap-2">
                <CheckCircle className="w-4 h-4 text-green-400" />
                2024 Season Data Loaded
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Navigation */}
      <div className="bg-black/10 backdrop-blur-lg border-b border-white/10">
        <div className="max-w-7xl mx-auto px-4">
          <div className="flex space-x-8">
            {[
              { id: 'predict', label: 'Predict Games', icon: Play },
              { id: 'optimize', label: 'Find Optimal Weights', icon: TrendingUp },
              { id: 'backtest', label: 'Backtest Model', icon: BarChart3 },
              { id: 'data', label: 'Data Overview', icon: Database }
            ].map(tab => {
              const Icon = tab.icon;
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`flex items-center gap-2 py-4 px-2 border-b-2 transition-colors ${
                    activeTab === tab.id 
                      ? 'border-orange-500 text-orange-400' 
                      : 'border-transparent text-gray-400 hover:text-white'
                  }`}
                >
                  <Icon className="w-5 h-5" />
                  {tab.label}
                </button>
              );
            })}
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto p-6">
        {/* Predict Tab */}
        {activeTab === 'predict' && (
          <div className="grid lg:grid-cols-3 gap-8">
            <div className="lg:col-span-1">
              <div className="bg-white/10 backdrop-blur-lg rounded-2xl p-6 border border-white/20">
                <h2 className="text-2xl font-bold mb-6 flex items-center gap-2">
                  <Settings className="w-6 h-6" />
                  Model Weights
                </h2>
                
                <div className="space-y-8">
                  <WeightSlider category="offense" label="Offense" value={weights.offense} color="#10b981" />
                  <WeightSlider category="defense" label="Defense" value={weights.defense} color="#f59e0b" />
                  <WeightSlider category="special_teams" label="Special Teams" value={weights.special_teams} color="#8b5cf6" />
                </div>

                <div className="mt-8 p-4 bg-green-500/20 rounded-xl border border-green-500/30">
                  <div className="flex items-center justify-between">
                    <span className="text-green-300 font-semibold">Total:</span>
                    <span className="text-2xl font-bold text-green-300">
                      {(weights.offense + weights.defense + weights.special_teams).toFixed(1)}%
                    </span>
                  </div>
                  <div className="flex items-center gap-2 mt-2 text-green-300 text-sm">
                    <Zap className="w-4 h-4" />
                    Ready to predict!
                  </div>
                </div>
              </div>
            </div>

            <div className="lg:col-span-2 space-y-6">
              <div className="bg-white/10 backdrop-blur-lg rounded-2xl p-6 border border-white/20">
                <h2 className="text-2xl font-bold mb-2 flex items-center gap-2">
                  <Calendar className="w-6 h-6" />
                  {PREDICT_SEASON} Games
                </h2>
                {predictData.degraded && (
                  <div className="mb-4 p-3 rounded-lg bg-yellow-500/10 border border-yellow-500/30 text-yellow-200 text-sm">
                    No {PREDICT_SEASON} games played yet — predictions use {predictData.statsSeason} season-end
                    team stats until {PREDICT_SEASON} data starts rolling in.
                  </div>
                )}
                <div className="grid gap-4">
                  {predictData.upcoming_games.slice(0, 16).map(game => {
                    const homeTeam = predictData.teams[game.home_team];
                    const awayTeam = predictData.teams[game.away_team];
                    if (!homeTeam || !awayTeam) return null;
                    
                    return (
                      <button
                        key={game.game_id}
                        onClick={() => setSelectedGame(game)}
                        className={`p-4 rounded-xl border transition-all ${
                          selectedGame?.game_id === game.game_id
                            ? 'border-orange-500 bg-orange-500/20'
                            : 'border-white/20 bg-white/5 hover:bg-white/10'
                        }`}
                      >
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-4">
                            <div className="text-2xl">🏈</div>
                            <div className="text-left">
                              <div className="font-semibold">{awayTeam.team_name}</div>
                              <div className="text-sm text-gray-400">@ {homeTeam.team_name}</div>
                            </div>
                          </div>
                          <div className="text-right">
                            <div className="font-semibold text-yellow-400">{game.week}</div>
                            <div className="text-sm text-gray-400">{game.game_date}</div>
                          </div>
                          <ChevronRight className="w-5 h-5 text-orange-500" />
                        </div>
                      </button>
                    );
                  })}
                </div>
              </div>

              {prediction && (
                <div className="bg-white/10 backdrop-blur-lg rounded-2xl p-6 border border-white/20">
                  <h2 className="text-2xl font-bold mb-6 flex items-center gap-2">
                    <Trophy className="w-6 h-6 text-yellow-500" />
                    Prediction Results
                  </h2>
                  
                  <div className="grid md:grid-cols-2 gap-6">
                    <div className="text-center">
                      <div className="text-6xl mb-4">🏆</div>
                      <h3 className="text-3xl font-bold text-green-400 mb-2">
                        {prediction.winner.team_name}
                      </h3>
                      <div className="bg-green-500/20 rounded-xl p-4 border border-green-500/30">
                        <div className="text-3xl font-bold text-green-300">
                          {prediction.confidence}%
                        </div>
                        <div className="text-green-200">Confidence</div>
                      </div>
                    </div>

                    <div className="space-y-4">
                      <h4 className="text-xl font-semibold">Model Scores</h4>
                      
                      <div className="flex items-center justify-between p-3 bg-white/5 rounded-lg">
                        <span>{prediction.homeTeam.team_abbr} (Home)</span>
                        <span className="font-mono text-lg">{prediction.homeScore}</span>
                      </div>
                      
                      <div className="flex items-center justify-between p-3 bg-white/5 rounded-lg">
                        <span>{prediction.awayTeam.team_abbr} (Away)</span>
                        <span className="font-mono text-lg">{prediction.awayScore}</span>
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </div>
          </div>
        )}

        {/* Optimize Tab */}
        {activeTab === 'optimize' && (
          <div className="bg-white/10 backdrop-blur-lg rounded-2xl p-6 border border-white/20">
            <div className="flex items-center justify-between mb-6">
              <div>
                <h2 className="text-2xl font-bold flex items-center gap-2 mb-2">
                  <TrendingUp className="w-6 h-6" />
                  Find Optimal Weight Distribution
                </h2>
                <p className="text-gray-300">
                  Analyze 2024 completed games to discover which weight combinations were most accurate
                </p>
              </div>
              <button
                onClick={findOptimalWeights}
                disabled={isAnalyzing}
                className="bg-orange-500 hover:bg-orange-600 disabled:bg-gray-500 px-6 py-3 rounded-xl font-semibold transition-colors"
              >
                {isAnalyzing ? 'Analyzing...' : 'Find Optimal Weights'}
              </button>
            </div>

            {isAnalyzing && (
              <div className="mb-6 p-4 bg-blue-500/20 rounded-xl border border-blue-500/30">
                <div className="animate-spin w-5 h-5 border-2 border-blue-400 border-t-transparent rounded-full inline-block mr-3"></div>
                <span className="text-blue-300 font-semibold">Testing Weight Combinations...</span>
              </div>
            )}

            {optimalWeights && (
              <div className="space-y-6">
                <div className="bg-green-500/20 rounded-2xl p-6 border border-green-500/30">
                  <h3 className="text-2xl font-bold text-green-300 mb-1">🏆 Best Weights (fit on {optimalWeights.fitSeason})</h3>
                  <p className="text-green-200/80 text-sm mb-4">
                    Chosen by {optimalWeights.fitSeason} results, then scored on the untouched {optimalWeights.testSeason} season.
                  </p>
                  <div className="grid md:grid-cols-2 gap-6">
                    <div>
                      <div className="space-y-3">
                        <div className="flex justify-between">
                          <span>Offense:</span>
                          <span className="font-bold text-green-400">{optimalWeights.best.offense}%</span>
                        </div>
                        <div className="flex justify-between">
                          <span>Defense:</span>
                          <span className="font-bold text-yellow-400">{optimalWeights.best.defense}%</span>
                        </div>
                        <div className="flex justify-between">
                          <span>Special Teams:</span>
                          <span className="font-bold text-purple-400">{optimalWeights.best.special_teams}%</span>
                        </div>
                      </div>
                      <button
                        onClick={() => setWeights({
                          offense: optimalWeights.best.offense,
                          defense: optimalWeights.best.defense,
                          special_teams: optimalWeights.best.special_teams
                        })}
                        className="mt-4 bg-green-500 hover:bg-green-600 px-4 py-2 rounded-lg font-semibold w-full"
                      >
                        Apply These Weights
                      </button>
                    </div>
                    <div className="text-center">
                      <div className="text-5xl font-bold text-green-300 mb-1">
                        {optimalWeights.honestAccuracy}%
                      </div>
                      <div className="text-green-200 text-sm font-semibold">
                        verified on the {optimalWeights.testSeason} season
                        <br />(untouched during fitting)
                      </div>
                      <div className="mt-4 flex justify-center gap-4 text-xs text-gray-300">
                        <span>Vegas favorite: <span className="font-bold text-gray-100">{optimalWeights.vegas}%</span></span>
                        <span className="text-gray-500">
                          in-sample {optimalWeights.fitSeason}: {optimalWeights.fitAccuracy}% (not real accuracy)
                        </span>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b border-white/20">
                        <th className="text-left p-3">Rank</th>
                        <th className="text-center p-3">Offense %</th>
                        <th className="text-center p-3">Defense %</th>
                        <th className="text-center p-3">Special Teams %</th>
                        <th className="text-center p-3 text-gray-400">{optimalWeights.fitSeason} fit</th>
                        <th className="text-center p-3 text-green-300">{optimalWeights.testSeason} honest</th>
                      </tr>
                    </thead>
                    <tbody>
                      {optimalWeights.allResults.map((result, idx) => (
                        <tr key={idx} className="border-b border-white/10">
                          <td className="p-3">#{idx + 1}</td>
                          <td className="p-3 text-center text-green-400">{result.weights.offense}%</td>
                          <td className="p-3 text-center text-yellow-400">{result.weights.defense}%</td>
                          <td className="p-3 text-center text-purple-400">{result.weights.special_teams}%</td>
                          <td className="p-3 text-center text-gray-400">{result.fit}%</td>
                          <td className="p-3 text-center font-bold text-green-300">{result.honest}%</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                  <p className="text-xs text-gray-500 mt-2">
                    Ranked by {optimalWeights.fitSeason} fit. Notice the gap: high {optimalWeights.fitSeason} numbers
                    don't guarantee high {optimalWeights.testSeason} numbers — that gap is why in-sample accuracy lies.
                  </p>
                </div>
              </div>
            )}

            {!optimalWeights && !isAnalyzing && (
              <div className="text-center py-12">
                <div className="text-6xl mb-4">⚡</div>
                <h3 className="text-xl font-semibold mb-2">Discover the Winning Formula</h3>
                <p className="text-gray-400">
                  Click "Find Optimal Weights" to fit factor combinations on the {FIT_SEASON} season,
                  then see how the best one holds up on the untouched {TEST_SEASON} season — the only accuracy that counts.
                </p>
              </div>
            )}
          </div>
        )}

        {/* Backtest Tab */}
        {activeTab === 'backtest' && (
          <div className="bg-white/10 backdrop-blur-lg rounded-2xl p-6 border border-white/20">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-2xl font-bold flex items-center gap-2">
                <BarChart3 className="w-6 h-6" />
                Model Backtesting
              </h2>
              <button
                onClick={runBacktest}
                className="bg-orange-500 hover:bg-orange-600 px-6 py-3 rounded-xl font-semibold"
              >
                Test Model
              </button>
            </div>

            {backtestResults && (
              <div className="space-y-6">
                <div className="text-center">
                  <div className="text-4xl font-bold text-green-300 mb-1">
                    {backtestResults.accuracy}%
                  </div>
                  <div className="text-green-200 text-lg">
                    your sliders on the {backtestResults.season} season (out-of-sample)
                  </div>
                  <div className="text-gray-400 text-sm mt-1">
                    {backtestResults.correct} of {backtestResults.total} correct — each pick uses only
                    prior weeks' results (Weeks 1–4 are model warm-up, no pick)
                  </div>
                  <div className="text-gray-400 text-sm mt-1">
                    for context — always picking the Vegas favorite hits {backtestResults.vegas}%
                  </div>
                </div>

                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b border-white/20">
                        <th className="text-left p-3">Game</th>
                        <th className="text-center p-3">Predicted</th>
                        <th className="text-center p-3">Actual</th>
                        <th className="text-center p-3">Result</th>
                      </tr>
                    </thead>
                    <tbody>
                      {backtestResults.results.map((game, idx) => (
                        <tr key={idx} className="border-b border-white/10">
                          <td className="p-3">{game.away_team} @ {game.home_team}</td>
                          <td className="p-3 text-center">{game.predicted}</td>
                          <td className="p-3 text-center">{game.winner}</td>
                          <td className="p-3 text-center">
                            <span className={`px-2 py-1 rounded text-xs font-bold ${
                              game.isCorrect ? 'bg-green-500/20 text-green-300' : 'bg-red-500/20 text-red-300'
                            }`}>
                              {game.isCorrect ? '✓' : '✗'}
                            </span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Data Tab */}
        {activeTab === 'data' && (
          <div className="bg-white/10 backdrop-blur-lg rounded-2xl p-6 border border-white/20">
            <h2 className="text-2xl font-bold mb-6 flex items-center gap-2">
              <Database className="w-6 h-6" />
              {predictData.statsSeason} NFL Data Overview
            </h2>

            <div className="grid md:grid-cols-2 gap-6">
              {Object.entries(predictData.teams).map(([abbr, team]: [string, any]) => (
                <div key={abbr} className="bg-white/5 rounded-lg p-4">
                  <h3 className="font-bold text-orange-400 mb-3">{team.team_name}</h3>
                  <div className="grid grid-cols-2 gap-2 text-sm">
                    <div>Record: {team.record.wins}-{team.record.losses}</div>
                    <div>PPG: {team.offense.points_per_game}</div>
                    <div>Pass Yds: {team.offense.passing_yards.toFixed(1)}</div>
                    <div>Rush Yds: {team.offense.rushing_yards.toFixed(1)}</div>
                    <div>Pts Allow: {team.defense.points_allowed_per_game.toFixed(1)}</div>
                    <div>Sacks: {team.defense.sacks}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default NFLPredictionApp;
                        